---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 16/09/23 11:07
---

---@class DataValidator

local DataValidator = {}

--- **Trunk Float To 2 Decimal**
---@param value double
---@return double
function DataValidator.trunkFloatTo2Decimal(value)
    return tonumber(string.format("%.2f", value)) + 0.0
end

--- **Is String**
---@param value string
---@return boolean
function DataValidator.isString(value)
    if type(value) ~= "string" then
        return false
    end

    return true
end

--- **Is Number**
---@param value number
---@return boolean
function DataValidator.isNumber(value)
    if type(value) ~= "number" then
        return false
    end

    return true
end

--- **Is Int**
---@param value int
---@return boolean
function DataValidator.isInt(value)
    if not DataValidator.isNumber(value) or
            math.floor(value) ~= value then
        return false
    end

    return true
end

--- **Is Double Or Float**
---@param value double or float
---@return boolean
function DataValidator.isDoubleFloat(value)
    if not DataValidator.isNumber(value) or not
    (value % 1 ~= 0) then
        return false
    end

    return true
end

return DataValidator
