---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 14/09/23 14:06
---

local dbgLeleLib = require("lib/DbgLeleLib")
local characterPz = require("lib/CharacterPZ")
local perkFactoryPZ = require("lib/PerkFactoryPZ")
local isoPlayerPZ = require("lib/IsoPlayerPZ")
local modDataManager = require("lib/ModDataManager")
local characterLib = require("CharacterLib")
require("lib/CharacterBaseObj")

---@type IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
local character = getPlayer()

--- **Character Update**
local function charaterUpdate()
    character = characterLib.charaterUpdate()
end

local function baseKnownRecipes()
    charaterUpdate()

    local recipe = "Make Pizza"

    characterPz.addKnownRecipe(character, recipe)

    charaterUpdate()

    ------- -------------------------------------------------------------
    local knownRecipes = characterPz.getKnowRecipes_PZ(character)

    if knownRecipes then
        for i = 0, knownRecipes:size() - 1  do
            dbgLeleLib.checkTest(knownRecipes:get(i), recipe, "KnownRecipes")
        end
    else
        dbgLeleLib.checkTest("", "1", "knownRecipes:size()")
    end

    characterPz.removeKnowRecipe_PZ(character, recipe)

    --- -------------------------------------------------------------
    dbgLeleLib.checkTest(character:getKnownRecipes():remove(recipe),
            false, "Remove KnowRecipe")

    charaterUpdate()
end

local function characterLibKnownRecipes()
    charaterUpdate()

    local recipe = "Make Pizza"

    characterPz.addKnownRecipe(character, recipe)

    charaterUpdate()

    local CharacterObj01 = CharacterBaseObj:new()
    CharacterObj01 = characterLib.getKnownRecipes(character)

    ---@type boolean
    local flag = false
    for _, v in pairs(CharacterObj01:getRecipes()) do
        if v == recipe then
            flag = true
        end
    end

    dbgLeleLib.checkTest(flag,
            true, "KnownRecipes")

    charaterUpdate()
end

local function testRecipe()
    local knownRecipes = characterPz.getKnowRecipes_PZ(character)

    local dbg

    for i = 0, knownRecipes:size() - 1  do
        print(knowRecipes:get(i))
    end
end

-- Perks.Maintenance
-- Perks.Woodwork
-- Perks.Sprinting
-- Todo 		self.character:playSound("CloseBook")
---@param character IsoGameCharacter
local function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g >  \n")
        testRecipe()
    end
end

---@param character IsoGameCharacter
local function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h >  \n")

    end
end

---@param character IsoGameCharacter
local function key36(character, key)
    if key == 36 then -- <<<< j
        print("Key = j > delete & create \n")
        dbgLeleLib.deleteCharacter()
        characterPz.setPerkLevelFromXp(character, Perks.Fitness, 37500)
        characterPz.setPerkLevelFromXp(character, Perks.Strength, 37500)
    end
end

---@param character IsoGameCharacter
local function key37(character, key)
    if key == 37 then -- <<<< k
        print("Key = k > kill \n")
        character:die()
    end
end

---@param character IsoGameCharacter
local function key16(character, key)
    if key == 16 then -- <<<< q
        print("Key = q >  \n")

    end
end

---@param character IsoGameCharacter
local function key17(character, key)
    if key == 17 then -- <<<< w
        print("Key = w >  \n")

    end
end

---@param character IsoGameCharacter
local function key18(character, key)
    if key == 18 then -- <<<< e
        print("Key = e >  \n")

    end
end

local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    --key16(character, key)
    --key17(character, key)
    --key18(character, key)
    --key34(character, key)
    --key35(character, key)
    --key36(character, key)
    --key37(character, key)
end

-- ------------------------------------------------------------
-- ------------------------------------------------------------

local function OnGameStart()

end

-- Events.OnGameStart.Add(OnGameStart)
Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)
