---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/09/23 21:38
---

local dataValidator = require("media.lua.shared.lib.DataValidator")

local value
dataValidator.isDoubleFloat(value)

-----@type table
--local datePartsConverted = {}
--
-----@type int
--local day = tonumber(dateParts[3])
--table.insert(datePartsConverted, day)
----print(day)
--
-----@type int
--local month = month[dateParts[2]]
--table.insert(datePartsConverted, month)
----print(month)
--
-----@type int
--local year = tonumber(dateParts[6])
--table.insert(datePartsConverted, year)
----print(year)
--
-- return datePartsConverted

-----------------------------------------------------------------------------

--local myDate = {
--    year = 2023,    -- L'anno (ad esempio 2023)
--    month = 9,      -- Il mese (da 1 a 12)
--    day = 12,       -- Il giorno del mese (da 1 a 31)
--    hour = 15,      -- L'ora (da 0 a 23)
--    min = 30,       -- I minuti (da 0 a 59)
--    sec = 0         -- I secondi (da 0 a 59)
--}
--
--local timestamp = os.time(myDate)
--print(timestamp) -- Stampa il timestamp Unix

-----------------------------------------------------------------------------

----- **Is String**
-----@param value string
-----@return boolean
--local function isString(value)
--    if type(value) ~= "string" then
--        return false
--    end
--
--    return true
--end
--
----- **Is Number**
-----@param value number
-----@return boolean
--local function isNumber(value)
--    if type(value) ~= "number" then
--        return false
--    end
--
--    return true
--end
--
----- **Is Int**
-----@param value int
-----@return boolean
--local function isInt(value)
--    if not isNumber(value) or
--            math.floor(value) ~= value then
--        return false
--    end
--
--    return true
--end
--
----- **Is Double Or Float**
-----@param value double or float
-----@return boolean
--local function isDoubleFloat(value)
--    if not isNumber(value) or not
--            (value % 1 ~= 0) then
--        return false
--    end
--
--    return true
--end
--
--print(isString("sss"))
--print(isInt(12))
--
--print(isNumber(12))
--print(isDoubleFloat(12.1))

-----------------------------------------------------------------------------